// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name string `json:"name"`
	Pwd  string `json:"pwd"`
}

type LoginResponse struct {
	Token   string `json:"token"`
	ReToken string `json:"reToken"`
	Role    int    `json:"role"`
}

type RegisterRequest struct {
	Name string `json:"name"`
	Pwd  string `json:"pwd"`
}

type RegisterResponse struct {
	Message string `json:"message"`
}

type CollyShowRequest struct {
	PageSize int64 `json:"pageSize"`
	PageNum  int64 `json:"pageNum"`
}

type Article struct {
	CreateTime  string `json:"createTime"`
	Title       string `json:"title"`
	Url         string `json:"url"`
	Description string `json:"description"`
}

type CollyShowResponse struct {
	TotalNum  int64     `json:"totalNum"`
	TotalSize int64     `json:"totalSize"`
	Data      []Article `json:"data"`
}
